name: "VQVAE"
lambda_euc2node: 0.5 #
lambda_euc2edge: 0.5 #
lambda_hyp2node: 0.5 #
lambda_hyp2edge: 0.5 #
lambda_consistency_node: 0.1 #
lambda_consistency_edge: 0.1 #
lambda_kl: 0.00 # kl loss
lambda_l2: 0.0 # l2 loss
lambda_band_norm: 0.0
lambda_vq_loss_weight: 1.0
codebook_size: 4096
lambda_commitment_weight: 0.25
lambda_orthogonal_reg_weight: 0.1
use_riemannian_optimizer: false
use_kmeans: false