name: "moses"
datadir: "data/moses/moses_pyg/" # Relative to the moses_dataset.py file
remove_h: null
filter: False
flow:
  train_max_epochs: 100
  batch_size:
    train: 256
    val: 1024
    test: 512
check_val_every_n_epochs: 2
debug: false
