name: "qm9" # qm9, qm9_positional
datadir: "data/qm9/qm9_pyg/"
remove_h: True
random_subset: null
pin_memory: False
debug: false
flow:
  train_max_epochs: 100
  batch_size:
    train: 256
    val: 256
    test: 256

check_val_every_n_epochs: 2
